version: '3.8'

services:
    router:
        image: itzg/mc-router:latest
        command: --in-docker-swarm
        ports:
            - '25565:25565'
        networks:
            - mc
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager

networks:
    mc:
        external: true
