version: '3.8'

networks:
    main:
        external: true

volumes:
    miniserve:

services:
    miniserve:
        image: docker.io/svenstaro/miniserve
        command: /data
        volumes:
            - miniserve:/data
        ports:
            - 8080
        stdin_open: true
        tty: true
        networks:
            - main
        labels:
            - 'hidden=true'
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.Hostname == ${NODE_HOSTNAME}
