version: '3.8'

networks:
    main:
        external: true

services:
    portainer-templates:
        image: ghcr.io/chickeniq/portainer-templates-server
        ports:
            - 80
        networks:
            - main
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.Hostname == ${NODE_HOSTNAME}
