version: '3.8'

volumes:
    data:

networks:
    mc:
        external: true

services:
    server:
        image: itzg/minecraft-server:${JAVA_VERSION}
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - data:/data
        networks:
            - mc
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - mc-router.host=${HOST}
            placement:
                constraints:
                    - node.Hostname == ${NODE_HOSTNAME}

        environment:
            VERSION: '${VERSION}'
            SPIGET_RESOURCES: '${SPIGET_RESOURCES}'

            MOTD: '${MOTD}'
            OPS: '${OPS}'
            WHITELIST: '${WHITELIST}'

            MAX_PLAYERS: '${MAX_PLAYERS}'
            DIFFICULTY: '${DIFFICULTY}'

            ENABLE_WHITELIST: '${ENABLE_WHITELIST}'
            ONLINE_MODE: '${ONLINE_MODE}'
            ALLOW_FLIGHT: '${ALLOW_FLIGHT}'
            ENABLE_COMMAND_BLOCK: '${ENABLE_COMMAND_BLOCK}'

            WORLD: '${WORLD}'
            SEED: '${SEED}'
            LEVEL_TYPE: '${LEVEL_TYPE}'
            GENERATOR_SETTINGS: '${GENERATOR_SETTINGS}'
            ALLOW_NETHER: '${ALLOW_NETHER}'

            VIEW_DISTANCE: '${VIEW_DISTANCE}'
            SPAWN_PROTECTION: '${SPAWN_PROTECTION}'
            MODE: '${MODE}'
            HARDCORE: '${HARDCORE}'
            FORCE_GAMEMODE: '${FORCE_GAMEMODE}'
            PVP: '${PVP}'

            SIMULATION_DISTANCE: '${SIMULATION_DISTANCE}'
            PLAYER_IDLE_TIMEOUT: '${PLAYER_IDLE_TIMEOUT}'

            SPAWN_NPCS: '${SPAWN_NPCS}'
            SPAWN_ANIMALS: '${SPAWN_ANIMALS}'
            SPAWN_MONSTERS: '${SPAWN_MONSTERS}'
            GENERATE_STRUCTURES: '${GENERATE_STRUCTURES}'

            RESOURCE_PACK: '${RESOURCE_PACK}'
            RESOURCE_PACK_ENFORCE: '${RESOURCE_PACK_ENFORCE}'

            OVERRIDE_SERVER_PROPERTIES: '${OVERRIDE_SERVER_PROPERTIES}'
            OVERRIDE_WHITELIST: '${OVERRIDE_WHITELIST}'
            OVERRIDE_ICON: '${OVERRIDE_ICON}'

            MAX_MEMORY: '${MAX_MEMORY}'
            INIT_MEMORY: '${INIT_MEMORY}'

            ICON: '${ICON}'
            EXEC_DIRECTLY: '${EXEC_DIRECTLY}'

            EULA: 'true'
            TYPE: PAPER
            ENFORCE_SECURE_PROFILE: 'false'
            SNOOPER_ENABLED: 'false'
