version: '3'
services:
  server:
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - ${PORT}:7777
    volumes:
      - data:/worlds
    environment:
      - worldname=${WORLD_NAME}
      - password=${PASSWORD}
      - motd=${MOTD}
      - seed=${SEED}
      - maxplayers=${MAX_PLAYERS}
      - autocreate=${WORLD_SIZE}
      - difficulty=${DIFFICULTY}
      - secure=${ALLOW_CHEATS}
      - world=/worlds/${WORLD_NAME}.wld
      - port=7777
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.Hostname ==  ${NODE_HOSTNAME}

volumes:
  data:
